#include "../include/OcaTypes.h"
#include "../include/OcaRoot.h"
#include "../include/classes/workers/OcaWorker.h"
#include "../include/classes/workers/actuators.h"
#include "../include/classes/workers/basicactuators.h"
#include "../include/classes/workers/sensors.h"
#include "../include/classes/workers/basicsensors.h"
#include "../include/classes/workers/blocks.h"
